[features]
seeds = false
skip-lint = false
[programs.localnet]
learn_anchor = "D4k3kCKpHCdoP5YxVRsR1fTRPB7NtTfCtp8cDLstfQms"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/yann/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
